CREATE DATABASE Pessoas;

USE Pessoas

CREATE TABLE Pessoas 
(
IdPessoa INT PRIMARY KEY IDENTITY 
,Nome	 VARCHAR(200) NOT NULL
)

CREATE TABLE Telefones
(
IdTelefone INT PRIMARY KEY IDENTITY
,Numero    VARCHAR(200)
,IdPessoa   INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)

CREATE TABLE Email
(
IdEmail	INT PRIMARY KEY IDENTITY
,Email  VARCHAR(200)
,IdPessoa INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)

CREATE TABLE CNH
(
IdCNH INT PRIMARY KEY IDENTITY
,CNH  VARCHAR(100)
,IdPessoa INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)